# Generated by Django 5.0 on 2023-12-23 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_productorder_productcart_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productorder',
            name='is_shipped',
            field=models.BooleanField(default=False),
        ),
    ]
