# Generated by Django 5.0 on 2023-12-27 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_productorder_country_productorder_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='payment',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('stripe', 'Stripe')], max_length=255, null=True),
        ),
    ]
