# Generated by Django 5.0 on 2023-12-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_productorder_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='payment',
            field=models.CharField(choices=[('paypal', 'PayPal')], max_length=255, null=True),
        ),
    ]
