# Generated by Django 5.0 on 2024-03-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_productorder_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manufacturer', 'Manufacturer'), ('owner', 'Owner')], default='owner', max_length=255),
        ),
    ]
