# Generated by Django 5.0 on 2024-03-23 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('archived', 'Archived')], default='pending', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='want_manufacturer',
            field=models.BooleanField(default=False),
        ),
    ]
