# Generated by Django 5.0 on 2024-03-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_product_status_user_want_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manufacturer', 'Manufacturer'), ('owner', 'Owner')], default='owner', max_length=255, null=True),
        ),
    ]
