# Generated by Django 5.0 on 2024-03-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('manufacturer', 'Manufacturer'), ('owner', 'Owner')], default='owner', max_length=255, null=True),
        ),
    ]
