# Generated by Django 5.0 on 2024-04-04 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_chatmessage_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='want_manufacturer',
        ),
    ]
